### ISSUE TITLE
support implace vector functions?

### ISSUE THREAD

**Issue by longemen3000** [francescoalemanno/FixedPoint.jl#3]
hi, i saw your discourse post and then the repository and im really like it. On our package, we had to add a fixed point solver (just with damping) to solve some [thermo problems](https://github.com/ypaul21/Clapeyron.jl/tree/master/src/solvers/fixpoint): , but i would be glad to depend on an external package instead, specially if it provides convergence advantages over simple and damped fixed point iterations.

While the vector solver provided in this package is fine, it allocates a vector on each call. this will quickly becomes the main bottleneck. one idea is to provide an "implace" version of `afps`, `afps!` that accepts a function `f!(out,x)`. then the function calls just overwrite a buffer vector instead of creating a new one.

**Comment by francescoalemanno** [comment]
I'll be happy to provide an inplace version, I'll work on it

**Comment by francescoalemanno** [comment]
<strike> I'll be happy to provide an inplace version, I'll work on it</strike>

@longemen3000 it should be done now, let me know how it goes :)
